CREATE TABLE IF NOT EXISTS  `variant` (
    `pdb_fn` VARCHAR NOT NULL,
    `mutations` VARCHAR NOT NULL,
    `job_uuid` VARCHAR NOT NULL,
    `start_time` DATETIME,
    `run_time` INT unsigned,
    `total_score` DECIMAL,
    `dslf_fa13` DECIMAL,
    `fa_atr` DECIMAL,
    `fa_dun` DECIMAL,
    `fa_elec` DECIMAL,
    `fa_intra_rep` DECIMAL,
    `fa_intra_sol_xover4` DECIMAL,
    `fa_rep` DECIMAL,
    `fa_sol` DECIMAL,
    `hbond_bb_sc` DECIMAL,
    `hbond_lr_bb` DECIMAL,
    `hbond_sc` DECIMAL,
    `hbond_sr_bb` DECIMAL,
    `lk_ball_wtd` DECIMAL,
    `omega` DECIMAL,
    `p_aa_pp` DECIMAL,
    `pro_close` DECIMAL,
    `rama_prepro` DECIMAL,
    `ref` DECIMAL,
    `yhh_planarity` DECIMAL,

    `filter_total_score` DECIMAL,
    `buried_all` DECIMAL,
    `buried_np` DECIMAL,
    `contact_all` DECIMAL,
    `contact_buried_core` DECIMAL,
    `contact_buried_core_boundary` DECIMAL,
    `degree` DECIMAL,
    `degree_core` DECIMAL,
    `degree_core_boundary` DECIMAL,
    `exposed_hydrophobics` DECIMAL,
    `exposed_np_AFIMLWVY` DECIMAL,
    `exposed_polars` DECIMAL,
    `exposed_total` DECIMAL,
    `one_core_each` DECIMAL,
    `pack` DECIMAL,
    `res_count_all` DECIMAL,
    `res_count_buried_core` DECIMAL,
    `res_count_buried_core_boundary` DECIMAL,
    `res_count_buried_np_core` DECIMAL,
    `res_count_buried_np_core_boundary` DECIMAL,
    `ss_contributes_core` DECIMAL,
    `ss_mis` DECIMAL,
    `total_hydrophobic` DECIMAL,
    `total_hydrophobic_AFILMVWY` DECIMAL,
    `total_sasa` DECIMAL,
    `two_core_each` DECIMAL,
    `unsat_hbond` DECIMAL,

    `centroid_total_score` DECIMAL,
    `cbeta` DECIMAL,
    `cenpack` DECIMAL,
    `env` DECIMAL,
    `hs_pair` DECIMAL,
    `linear_chainbreak` DECIMAL,
    `overlap_chainbreak` DECIMAL,
    `pair` DECIMAL,
    `rg` DECIMAL,
    `rsigma` DECIMAL,
    `sheet` DECIMAL,
    `ss_pair` DECIMAL,
    `vdw` DECIMAL,

    PRIMARY KEY (`pdb_fn`,`mutations`,`job_uuid`),
    FOREIGN KEY (`pdb_fn`) REFERENCES pdb_file(`pdb_fn`),
    FOREIGN KEY (`job_uuid`) REFERENCES job(`uuid`));

CREATE TABLE IF NOT EXISTS  `pdb_file` (
    `pdb_fn` VARCHAR,
    `aa_sequence` VARCHAR,
    `seq_len` INT unsigned,
    PRIMARY KEY (`pdb_fn`));

CREATE TABLE IF NOT EXISTS  `job` (
    `uuid` VARCHAR,
    `hparam_set_id` VARCHAR,
    `cluster` VARCHAR,
    `process` VARCHAR,
    `hostname` VARCHAR,
    `github_tag` VARCHAR,
    `script_start_time` DATETIME,
    PRIMARY KEY (`uuid`),
    FOREIGN KEY (`hparam_set_id`) REFERENCES rosetta_hparam_set(`id`));

CREATE TABLE IF NOT EXISTS  `rosetta_hparam_set` (
    `id` INT unsigned AUTO_INCREMENT,
    `mutate_default_max_cycles` INT unsigned,
    `relax_repeats` INT unsigned,
    `relax_nstruct` INT unsigned,
    `relax_distance` DECIMAL,
    PRIMARY KEY (`id`));